robot:
  # Basic robot configuration
  name: aloha_solo                # Unique identifier for the robot
  fps: 50                         # Frames per second for system updates

  # Leader Arm Configuration
  leader_arms:
    - name: leader_solo           # Unique name for the solo leader arm
      model: aloha_wx250s         # Model type for compatibility and calibration
      orientation: right          # Orientation/side of the arm
      transform: [-0.5, -0.25, 0.0, 0.0, 0.0, 0.0, 1.0]  # Transformation matrix for spatial alignment

  # Follower Arm Configuration
  follower_arms:
    - name: follower_solo         # Unique name for the solo follower arm
      model: aloha_vx300s         # Model type for compatibility and calibration
      orientation: right          # Orientation/side of the arm
      transform: [0.5, -0.25, 0.0, 0.0, 0.0, 0.0, 1.0]  # Transformation matrix for spatial alignment

  # Camera Configuration
  cameras:
    # Common parameters for all camera instances
    common_parameters:
      enable_color: true                     # Enable color camera mode
      rgb_camera:
        profile: '640,480,60'                # Resolution and FPS for RGB camera
        enable_auto_exposure: false          # Disable auto exposure for consistent lighting
      depth_module:
        profile: '640,480,60'                # Resolution and FPS for depth module
        enable_auto_exposure: false          # Disable auto exposure for depth consistency
      enable_depth: false                    # Overall depth mode status (true or false)
      enable_infra: false                    # Infrared camera setting (primary)
      enable_infra1: false                   # Infrared camera setting (secondary, IR1)
      enable_infra2: false                   # Infrared camera setting (secondary, IR2)
      color_image_topic_name: '{}/camera/color/image_rect_raw'  # Topic format for color images

    # Individual camera instances with unique parameters
    camera_instances:
      - name: camera_wrist_right             # Identifier for the right wrist camera
        serial_no: "130322272300"            # Serial number for device identification

      - name: camera_high                    # Identifier for a high-position camera
        serial_no: "130322274102"            # Serial number for device identification

  # Base Configuration
  base: false                                # Status of base usage (whether robot has a base or not)
