robot_name: aloha_remote

follower_arms:
  - name: follower_remote
    model: aloha_vx300s
    modes: follower_modes_right.yaml
    motor_configs: aloha_vx300s.yaml
    transform: [0.5, -0.25, 0.0, 0.0, 0.0, 0.0, 1.0]

leader_arms:
  - name: leader_remote
    model: aloha_wx250s
    modes: leader_modes_right.yaml
    motor_configs: aloha_wx250s.yaml
    motor_specs: leader_motor_specs_right.yaml
    transform: [-0.5, -0.25, 0.0, 0.0, 0.0, 0.0, 1.0]


cameras:
  common_parameters:  # Common settings applied to all cameras
    enable_color: true
    rgb_camera:
      profile: '640,480,60'
      enable_auto_exposure: false
    depth_module:
      profile: '640,480,60'
      enable_auto_exposure: false
    enable_depth: false
    enable_infra: false
    enable_infra1: false
    enable_infra2: false
    color_image_topic_name : '{}/camera/color/image_rect_raw' 


  camera_instances:
    
    - name: camera_wrist_right
      serial_no: "218622272670"
      

base: false
