robot_name: aloha_solo
fps: 50
leader_arms:
  - name: leader_solo
    model: aloha_wx250s
    transform: [-0.5, -0.25, 0.0, 0.0, 0.0, 0.0, 1.0]
    orientation: right

follower_arms:
  - name: follower_solo
    model: aloha_vx300s
    transform: [0.5, -0.25, 0.0, 0.0, 0.0, 0.0, 1.0]
    orientation: right


cameras:
  common_parameters:  # Common settings applied to all cameras
    enable_color: true
    rgb_camera:
      profile: '640,480,60'
      enable_auto_exposure: false
    depth_module:
      profile: '640,480,60'
      enable_auto_exposure: false
    enable_depth: false
    enable_infra: false
    enable_infra1: false
    enable_infra2: false
    color_image_topic_name : '{}/camera/color/image_rect_raw' 



  camera_instances:
    
    - name: camera_wrist_right
      serial_no: "130322272300"
    
    - name: camera_high
      serial_no: "130322274102"
      

base: false
